[package]
name = "ra-test"
version = "0.1.0"
edition = "2024"

[dependencies]

embassy-rp = { version = "0.10.0", features = [
    "log",
    "unstable-pac",
    "time-driver",
    "critical-section-impl",
    "rp235xa",
    "binary-info",
] }
embassy-executor = { version = "0.10.0", features = [
    "platform-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt",
] }

embassy-embedded-hal = "0.6.0"
embedded-hal-async = "1.0.0"

cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7.0"

panic-halt = "1.0.0"

heapless = { version = "0.9.2", features = ["serde"] }
